appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.2.3
appReplicas: 1
containerPort: 8080
containerEnvVars:
 - name: PORT  
   value: "8080"
 
servicePort: 8080
serviceType: ClusterIP 